### ISSUE TITLE
boot failed

### ISSUE THREAD

**Issue by weibaogang** [android-rpi/local_manifests#10]
I follow your method for pi2 transplant android system, but can not start the normal start, serial terminal print log as shown below, the screen no display @peyo-hd 

[   15.531679] init: Starting service 'surfaceflinger'...
[   15.538099] init: property_set("ro.build.product", "rpi2") failed
[   15.544337] init: property_set("ro.product.device", "rpi2") failed
[   15.551421] init: Starting service 'adbd'...
[   15.557761] init: Starting service 'console'...
[   15.564051] init: Starting service 'netd'...
[   15.571359] init: Starting service 'debuggerd'...
[   15.577403] init: cannot find '/system/bin/debuggerd64', disabling 'debuggerd64'
[   15.584982] init: cannot find '/system/bin/rild', disabling 'ril-daemon'
[   15.592692] init: Starting service 'drm'...
[   15.598669] init: Starting service 'media'...
[   15.604797] init: Starting service 'installd'...
[   15.611374] init: cannot find '/system/bin/install-recovery.sh', disabling 'flash_recovery'
[   15.621052] init: Starting service 'keystore'...
[   15.627555] init: Starting service 'zygote'...
[   15.633801] init: Starting service 'gatekeeperd'...
[   15.663778] logd.daemon: reinit
[   15.677146] init: Starting service 'perfprofd'...
[   15.682963] init: Service 'logd-reinit' (pid 89) exited with status 0
shell@rpi2:/ $ [   15.884282] random: perfprofd urandom read with 70 bits of entropy available
[   16.522323] healthd: No charger supplies found
[   16.526927] healthd: No battery devices found
[   17.426525] init: Service 'surfaceflinger' (pid 93) killed by signal 6
[   17.433159] init: Service 'surfaceflinger' (pid 93) killing any children in process group
[   17.446122] init: Service 'zygote' is being killed...
[   17.457575] init: Service 'zygote' (pid 104) killed by signal 9
[   17.463679] init: Service 'zygote' (pid 104) killing any children in process group
[   17.471696] init: write_file: Unable to open '/sys/android_power/request_state': No such file or directory
[   17.482465] init: write_file: Unable to open '/sys/power/state': No such file or directory
[   17.491218] init: Service 'media' is being killed...
[   17.496733] init: Service 'netd' is being killed...
[   17.503476] init: Service 'media' (pid 100) killed by signal 9
[   17.509562] init: Service 'media' (pid 100) killing any children in process group
[   17.518267] init: Service 'netd' (pid 96) killed by signal 9
[   17.523963] init: Service 'netd' (pid 96) killing any children in process group
[   17.532502] init: Untracked pid 177 killed by signal 9

**Comment by qhuyduong** [comment]
Hi,
I have been able to make this android source run on RPi2. Just by replacing the device tree file name in "config.txt" from "device_tree=bcm2710-rpi-3-b.dtb" to "device_tree=bcm2709-rpi-2-b.dtb"

Thanks

**Comment by Kiddduuu** [comment]
Even i am facing same issue. @weibaogang Did it solve for you? If so, how did you solve that?

**Comment by weibaogang** [comment]
@Kiddduuu Yes, I finally solved it .But I solved it by downloading the source code again .

**Comment by admcilgin** [comment]
I have a problem about HDMI display not showing , i tried peyo-hd solitions but not working , i connected the rpi to TV via HDMI .
