### ISSUE TITLE
Is there any place that I can just download the built image?

### ISSUE THREAD

**Issue by kernel-cyrus** [android-rpi/local_manifests#28]
I'm a kernel developer, I want just download the android built images (systme.img, vendor.img...), so that I don't need to download and compile the whole aosp. Is there any place like https://ci.android.com/?

**Comment by NellowTCS** [comment]
yeah same

**Comment by yanzhiwei1990** [comment]
严治威已收到来信，谢谢！

**Comment by NellowTCS** [comment]
> I'm a kernel developer, I want just download the android built images (systme.img, vendor.img...), so that I don't need to download and compile the whole aosp. Is there any place like https://ci.android.com/?

did you find any images or did you build them?
